


CREATE TABLE signalo_vl.durability
(
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  active boolean default true,
  value_en text,
  value_fr text,
  value_de text
);

INSERT INTO signalo_vl.durability (id, value_en, value_fr, value_de) VALUES (1, 'unknown', 'inconnu', 'unknown');
INSERT INTO signalo_vl.durability (id, active, value_en, value_fr, value_de) VALUES (2, false, 'other', 'autre', 'other');
INSERT INTO signalo_vl.durability (id, value_en, value_fr, value_de) VALUES (3, 'to be determined', 'à déterminer', 'to be determined');

INSERT INTO signalo_vl.durability (id, value_en, value_fr, value_de) VALUES (10, 'permanent', 'permanent', 'permanent');
INSERT INTO signalo_vl.durability (id, value_en, value_fr, value_de) VALUES (11, 'temporary', 'temporaire', 'temporary');
INSERT INTO signalo_vl.durability (id, value_en, value_fr, value_de) VALUES (12, 'winter', 'hivernal', 'winter');
