
-- https://www.signal.ch/content/uploads/2020/06/Signal_KAP4_062020.pdf

CREATE TABLE signalo_vl.mirror_shape
(
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  active boolean default true,
  value_de text,
  value_fr text,
  value_it text,
  value_ro text
);

INSERT INTO signalo_vl.mirror_shape (id, value_de, value_fr, value_it, value_ro) VALUES (2, 'TBD', 'autre', 'TBD', 'TBD');


INSERT INTO signalo_vl.mirror_shape (id, value_de, value_fr, value_it, value_ro) VALUES (11, 'TBD', 'rectangulaire', 'TBD', 'TBD');
INSERT INTO signalo_vl.mirror_shape (id, value_de, value_fr, value_it, value_ro) VALUES (12, 'TBD', 'circulaire', 'TBD', 'TBD');
