

-- see https://www.astra.admin.ch/astra/fr/home/documentation/regles-de-la-circulation/signaux.html

CREATE TABLE siro_vl.official_sign
(
  id text primary key,
  active boolean default true,
  value_en text,
  value_fr text,
  value_de text,
  description_en text,
  description_fr text,
  description_de text,
  img text
);


INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('1.01', '', 'Virage à droite', '', '101.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('1.02', '', 'Virage à gauche', '', '102.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('1.03', '', 'Double virage, le premier à droite', '', '103.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('1.04', '', 'Double virage, le premier à gauche', '', '104.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('1.05', '', 'Chaussée glissante', '', '105.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('1.06', '', 'Cassis', '', '106.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('1.07', '', 'Chaussée rétrécie', '', '107.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('1.08', '', 'Chaussée rétrécie à droite', '', '108.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('1.09', '', 'Chaussée rétrécie à gauche', '', '109.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('1.10', '', 'Descente dangereuse', '', '110.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('1.11', '', 'Forte montée', '', '111.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('1.12', '', 'Gravillon', '', '112.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('1.13', '', 'Chute de pierres', '', '113.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('1.14', '', 'Travaux', '', '114.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('1.15', '', 'Barrières', '', '115.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('1.16', '', '[[Passage à niveau]] sans barrières', '', '116.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('1.17', '', 'Panneaux indicateurs de distance', '', '117.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('1.18', '', 'Tramway ou chemin de fer routier', '', '118.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('1.22', '', 'Passage pour piétons', '', '122.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('1.23', '', 'Enfants', '', '123.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('1.24', '', 'Passage de [[gibier]]', '', '124.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('1.25', '', '[[Animal|Animaux]]', '', '125.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('1.25a', '', '[[Animal|Animaux]] (variante)', '', '125a.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('1.26', '', 'Circulation en sens inverse', '', '126.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('1.27', '', 'Signaux lumineux', '', '127.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('1.28', '', 'Avions', '', '128.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('1.29', '', '[[Vent]] latéral', '', '129.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('1.30', '', 'Autres [[Danger|dangers]]', '', '130.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('1.31', '', '[[Embouteillage_(route)|Bouchon]]', '', '131.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('1.32', '', '[[Cyclisme|Cyclistes]]', '', '132.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.01', '', 'Interdiction générale de circuler dans les deux sens', '', '201.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.02', '', 'Accès interdit', '', '202.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.03', '', 'Circulation interdite aux voitures automobiles', '', '203.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.04', '', 'Circulation interdite aux motocycles', '', '204.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.05', '', 'Circulation interdite aux cycles et cyclomoteurs', '', '205.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.06', '', 'Circulation interdite aux cyclomoteurs', '', '206.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.07', '', 'Circulation interdite aux camions', '', '207.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.08', '', 'Circulation interdite aux autocars', '', '208.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.09', '', 'Circulation interdite aux remorques', '', '209.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.09.1', '', 'Circulation interdite aux remorques autres que les semi-remorques et les remorques à essieu central', '', '209.1.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.10.1', '', 'Circulation interdite aux véhicules transportant des marchandises dangereuses', '', '210.1.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.11', '', 'Circulation interdite aux véhicules dont le chargement peut altérer les eaux', '', '211.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.12', '', 'Circulation interdite aux animaux', '', '212.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.13', '', 'Circulation interdite aux voitures automobiles et aux motocycles', '', '213.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.14', '', 'Circulation interdite aux voitures automobiles, aux motocycles et cyclomoteurs', '', '214.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.15', '', 'Accès interdit aux piétons', '', '215.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.15.1', '', 'Interdiction de skier', '', '215.1.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.15.2', '', 'Interdiction de luger', '', '215.2.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.15.3', '', 'Circulation interdite aux engins assimilés à des véhicules', '', '215.3.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.16', '', 'Poids maximal', '', '216.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.17', '', 'Charge par essieu', '', '217.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.18', '', 'Largeur maximale', '', '218.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.19', '', 'Hauteur maximale', '', '219.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.20', '', 'Longueur maximale', '', '220.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.30', '', 'Vitesse maximale', '', '230.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.30.1', '', 'Vitesse maximale 50, Limite générale', '', '230.1.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.31', '', 'Vitesse minimale', '', '231.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.32', '', 'Sens obligatoire à droite', '', '232.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.33', '', 'Sens obligatoire à gauche', '', '233.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.34', '', 'Obstacle à contourner par la droite', '', '234.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.35', '', 'Obstacle à contourner par la gauche', '', '235.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.36', '', 'Circuler tout droit', '', '236.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.37', '', 'Obliquer à droite', '', '237.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.38', '', 'Obliquer à gauche', '', '238.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.39', '', 'Obliquer à droite ou à gauche', '', '239.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.40', '', 'Circuler tout droit ou obliquer à droite', '', '240.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.41', '', 'Circuler tout droit ou obliquer à gauche', '', '241.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.41.1', '', 'Carrefour à sens giratoire', '', '241.1.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.41.2', '', 'Sens obligatoire pour les véhicules transportant des marchandises dangereuses', '', '241.2.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.42', '', 'Interdiction d''obliquer à droite', '', '242.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.43', '', 'Interdiction d''obliquer à gauche', '', '243.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.44', '', 'Interdiction de dépasser', '', '244.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.45', '', 'Interdiction aux camions de dépasser', '', '245.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.46', '', 'Interdiction de faire demi-tour', '', '246.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.47', '', 'Distance minimale', '', '247.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.48', '', 'Chaînes à neige obligatoires', '', '248.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.49', '', 'Interdiction de s''arrêter', '', '249.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.50', '', 'Interdiction de parquer', '', '250.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.51', '', 'Arrêt à proximité d''un poste de douane', '', '251.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.52', '', 'Police', '', '252.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.53', '', 'Fin de la vitesse maximale', '', '253.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.53.1', '', 'Fin de la vitesse maximale 50, Limite générale', '', '253.1.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.54', '', 'Fin de la vitesse minimale', '', '254.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.55', '', 'Fin de l''interdiction de dépasser', '', '255.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.56', '', 'Fin de l''interdiction aux camions de dépasser', '', '256.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.56.1', '', 'Fin de l''interdiction partielle de circuler', '', '256.1.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.57', '', 'Fin de l''obligation d’utiliser des chaînes à neige', '', '257.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.58', '', 'Libre circulation', '', '258.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.59.1', '', 'Signal de zone', '', '259.1.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.59.1', '', 'Signal de zone (variante, uniquement en Suisse)', '', '259.1.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.59.1', '', 'Signal de zone (variante, uniquement en Suisse)', '', '259.1.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.59.2', '', 'Signal de fin de zone', '', '259.2.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.59.2', '', 'Ende-Zonensignal (Variation, nur Schweiz)', '', '259.2.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.59.2', '', 'Ende-Zonensignal (Variation, nur Schweiz)', '', '259.2.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.59.3', '', 'Zone piétonne', '', '259.3.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.59.4', '', 'Fin de la zone piétonne', '', '259.4.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.59.5', '', 'Zone de rencontre', '', '259.5.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.59.6', '', 'Fin de la zone de rencontre', '', '259.6.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.60', '', 'Piste cyclable', '', '260.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.60.1', '', 'Fin de la piste cyclable', '', '260.1.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.61', '', 'Chemin pour piétons', '', '261.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.62', '', 'Allée d''équitation', '', '262.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.63', '', 'Piste cyclable et chemin pour piétons, avec partage de l''aire de circulation', '', '263.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.63.1', '', 'Piste cyclable et chemin pour piétons sans partage de l''aire de circulation', '', '263.1.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.64', '', 'Chaussée réservée aux bus', '', '264.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.65', '', 'Système de signaux lumineux pour la fermeture temporaire des voies de circulation', '', '265.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.30.1', '', 'Vitesse maximale 50, limite générale (f)', '', '230.1.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.30.1', '', 'Vitesse maximale 50, limite générale (i)', '', '230.1.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.30.1', '', 'Vitesse maximale 50, limite générale (r)', '', '230.1.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.53.1', '', '(f) Fin de la vitesse maximale 50, Limite générale', '', '253.1.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.53.1', '', '(i) Fin de la vitesse maximale 50, Limite générale', '', '253.1.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.53.1', '', '(r) Fin de la vitesse maximale 50, Limite générale', '', '253.1.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.51', '', 'Arrêt à proximité d''un poste de douane', '', '251.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.52', '', 'Police', '', '252.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.59.1', '', '(i/r) Signal de zone', '', '259.1.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.59.1', '', '(i/r) Signal de zone (Variante)', '', '259.1.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.59.1', '', '(i/r) Signal de zone (Variante)', '', '259.1.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.59.2', '', '(i/r) Signal de fin de zone', '', '259.2.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.59.2', '', '(i/r) Signal de fin de zone (Variante)', '', '259.2.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.59.2', '', '(i/r) Signal de fin de zone (Variante)', '', '259.2.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.59.3', '', '(i/r) Zone piétonne', '', '259.3.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.59.4', '', '(i/r) Fin de la zone piétonne', '', '259.4.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.59.5', '', '(i/r) Zone de rencontre', '', '259.5.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('2.59.6', '', '(i/r) Fin de la zone de rencontre', '', '259.6.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('3.01', '', 'Stop', '', '301.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('3.02', '', 'Cédez le passage', '', '302.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('3.03', '', 'Route principale', '', '303.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('3.04', '', 'Fin de la route principale', '', '304.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('3.05', '', 'Intersection avec une route sans priorité', '', '305.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('3.06', '', 'Intersection comportant la priorité de droite', '', '306.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('3.07', '', 'Entrée par la droite', '', '307.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('3.08', '', 'Entrée par la gauche', '', '308.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('3.09', '', 'Laissez passer les véhicules en sens inverse', '', '309.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('3.10', '', 'Priorité par rapport aux véhicules venant en sens inverse', '', '310.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('3.20', '', 'Signal à feux clignotant alternativement', '', '320.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('3.21', '', 'Signal à feu clignotant simple', '', '321.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('3.22', '', 'Croix de St-André simple', '', '322.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('3.23', '', 'Croix de St-André double', '', '323.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('3.24', '', 'Croix de St-André simple', '', '324.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('3.25', '', 'Croix de St-André double', '', '325.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.01', '', 'Autoroute', '', '401.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.02', '', 'Fin de l''autoroute', '', '402.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.03', '', 'Semi-autoroute', '', '403.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.04', '', 'Fin de la semi-autoroute', '', '404.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.05', '', 'Route postale de montagne', '', '405.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.06', '', 'Fin de la route postale de montagne', '', '406.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.07', '', 'Tunnel', '', '407.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.08', '', 'Sens unique', '', '408.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.08.1', '', 'Sens unique avec circulation de cyclistes en sens inverse', '', '408.1.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.09', '', '[[Impasse]]', '', '409.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.10', '', 'Zone de protection des eaux', '', '410.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.11', '', 'Emplacement d''un [[passage pour piétons]]', '', '411.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.12', '', 'Passage souterrain pour piétons', '', '412.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.13', '', 'Passerelle pour piétons', '', '413.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.14', '', 'Hôpital', '', '414.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.15', '', 'Place d''évitement', '', '415.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.16', '', 'Place d''arrêt pour véhicules en panne', '', '416.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.17', '', 'Parcage autorisé', '', '417.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.18', '', 'Parcage avec disque de stationnement', '', '418.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.19', '', 'Fin du parcage avec disque de stationnement', '', '419.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.20', '', 'Parcage contre paiement', '', '420.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.21', '', 'Parking couvert', '', '421.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.22', '', 'Distance et direction d''un parking', '', '422.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.23', '', 'Indicateur de direction avancé pour des genres de véhicules déterminés', '', '423.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.24', '', 'Voie de détresse', '', '424.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.25', '', 'Parking avec accès aux transports publics', '', '425.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.27', '', 'Début de localité sur route principale (Suisse)', '', '427.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.28', '', 'Fin de localité sur route principale (Suisse)', '', '428.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.29', '', 'Début de localité sur route secondaire (Suisse)', '', '429.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.30', '', 'Fin de localité sur route secondaire (Suisse)', '', '430.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.27', '', 'Début de localité sur route principale (Liechtenstein)', '', '427.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.28', '', 'Fin de localité sur route principale (Liechtenstein)', '', '428.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.29', '', 'Début de localité sur route secondaire (Liechtenstein)', '', '429.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.30', '', 'Fin de localité sur route secondaire (Liechtenstein)', '', '430.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.31', '', 'Indicateur de direction pour autoroutes et semi-autoroutes', '', '431.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.32', '', 'Indicateur de direction pour routes principales', '', '432.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.33', '', 'Indicateur de direction pour routes secondaires', '', '433.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.34', '', 'Indicateur de direction pour déviation', '', '434.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.34.1', '', ' Indicateur de direction pour déviation sans mention du lieu de destination', '', '434.1.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.35', '', 'Indicateur de direction en forme de tableau', '', '435.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.36', '', 'Indicateur de direction avancé sur route principale', '', '436.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.37', '', 'Indicateur de direction avancé sur route secondaire', '', '437.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.38', '', 'Indicateur de direction avancé avec répartition des voies sur route principale', '', '438.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.39', '', 'Indicateur de direction avancé avec répartition des voies sur route secondaire', '', '439.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.40', '', 'Indicateur de direction avancé annonçant des restrictions', '', '440.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.41', '', 'Panneau de présélection au-dessus d''une voie de circulation sur route principale', '', '441.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.42', '', 'Panneau de présélection au-dessus d''une voie de circulation sur route secondaire', '', '442.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.45', '', ' Indicateur de direction pour des genres de véhicules déterminés', '', '445.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.46', '', 'Indicateur de direction «Place de stationnement', '', '446.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.46.1', '', 'Indicateur de direction «Parking avec accès aux transports publics»', '', '446.1.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.47', '', 'Indicateur de direction «Place de camping»', '', '447.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.48', '', 'Indicateur de direction «Terrain pour caravanes»', '', '448.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.49', '', 'Indicateur de direction «Entreprise»', '', '449.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.50.1', '', 'Indicateur de direction «Itinéraire recommandé aux cyclistes»', '', '450.1.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.50.3', '', 'Indicateur de direction «Itinéraire pour vélos tout terrain»', '', '450.3.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.50.4', '', 'Indicateur de direction «Itinéraire pour engins assimilés à des véhicules»', '', '450.4.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.50.5', '', 'Indicateur de direction en forme de tableau destiné à un seul cercle d''usagers', '', '450.5.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.50.6', '', 'Indicateur de direction en forme de tableau destiné à plusieurs cercles d''usagers', '', '450.6.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.51.1', '', 'Indicateur de direction sans destination', '', '451.1.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.51.2', '', 'Indicateur de direction avancé sans destination', '', '451.2.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.51.3', '', 'Plaque de confirmation', '', '451.3.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.51.4', '', 'Plaque indiquant la fin d''un itinéraire', '', '451.4.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.52', '', 'Guidage du trafic', '', '452.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.53', '', 'Indicateur de direction avancé annonçant une déviation', '', '453.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.54', '', 'Indicateur de direction avancé pour carrefour à sens giratoire', '', '454.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.55', '', 'Route latérale comportant un danger ou une restriction', '', '455.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.56', '', 'Plaque numérotée pour routes européennes', '', '456.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.57', '', 'Plaque numérotée pour routes principales', '', '457.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.58', '', 'Plaque numérotée pour autoroutes et semi- autoroutes', '', '458.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.59', '', 'Plaque numérotée pour jonctions', '', '459.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.59.1', '', 'Plaque numérotée pour ramifications', '', '459.1.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.60', '', 'Panneau annonçant la prochaine jonction', '', '460.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.61', '', 'Indicateur de direction avancé, destiné aux jonctions', '', '461.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.62', '', 'Indicateur de direction avancé destiné aux jonctions', '', '462.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.63', '', 'Panneau indicateur de sortie', '', '463.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.64', '', 'Panneau de bifurcation', '', '464.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.65', '', 'Panneau des distances en kilomètres', '', '465.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.66', '', 'Panneau de ramification', '', '466.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.67', '', 'Premier indicateur de direction avancé, destiné aux ramifications', '', '467.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.68', '', 'Deuxième indicateur de direction avancé, destiné aux ramifications', '', '468.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.69', '', 'Panneau de présélection au- dessus d''une voie de circulation sur autoroute et semi-autoroute', '', '469.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.70', '', 'Plaque indiquant un téléphone de secours', '', '470.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.71', '', 'Panneau indiquant un centre de police', '', '471.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.72', '', 'Plaque indiquant le nombre de kilomètres', '', '472.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.73', '', 'Plaque indiquant le nombre d''hectomètres', '', '473.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.75', '', 'Etat de la route', '', '475.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.76', '', 'Préavis sur l''état de la route', '', '476.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.77', '', 'Disposition des voies de circulation', '', '477.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.77.1', '', 'Disposition des voies de circulation annonçant des restrictions', '', '477.1.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.79', '', '[[Place de camping]]', '', '479.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.80', '', 'Terrain pour caravanes', '', '480.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.81', '', 'Téléphone', '', '481.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.82', '', 'Premiers secours', '', '482.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.83', '', '[[Poste de dépannage]]', '', '483.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.84', '', '[[Poste d''essence]]', '', '484.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.85', '', 'Hôtel-Môtel', '', '485.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.86', '', 'Restaurant', '', '486.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.87', '', 'Rafraîchissement', '', '487.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.88', '', 'Poste d''information', '', '488.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.89', '', '[[Auberge de jeunesse]]', '', '489.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.90', '', 'Bulletin routier radiophonique', '', '490.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.91', '', 'Service religieux', '', '491.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.92', '', 'Extincteur', '', '492.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.93', '', 'Information sur les limitations générales de vitesse', '', '493.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.94', '', 'Direction et distance vers l''issue de secours la plus proche', '', '494.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('4.95', '', 'Issue de secours', '', '495.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('5.01', '', 'Plaque de distance', '', '501.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('5.02', '', 'Plaque indiquant la distance et la direction', '', '502.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('5.03', '', 'Longueur du tronçon', '', '503.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('5.04', '', 'Plaque de rappel', '', '504.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('5.05', '', 'Plaque indiquant le début d''une prescription', '', '505.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('5.06', '', ' Plaque indiquant la fin d''une prescription', '', '506.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('5.07', '', 'Plaque de direction', '', '507.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('5.09', '', 'Direction de la route principale', '', '509.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('5.10', '', 'Dérogation à l''interdiction de s''arrêter', '', '510.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('5.11', '', 'Dérogation à l''inter- diction de parquer', '', '511.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('5.12', '', 'Feux clignotants', '', '512.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('5.13', '', 'Chaussée verglacée', '', '513.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('5.14', '', 'Handicapés', '', '514.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('5.15', '', 'Largeur de la chaussée', '', '515.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('5.16', '', 'Bruit de tirs', '', '516.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('5.17', '', 'Poste d''essence suivant', '', '517.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('5.20', '', 'Voiture automobile légère', '', '520.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('5.21', '', 'Voitures automobiles lourdes', '', '521.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('5.22', '', 'Camion', '', '522.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('5.23', '', 'Camion avec remorque', '', '523.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('5.24', '', 'Véhicule articulé', '', '524.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('5.25', '', 'Autocar', '', '525.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('5.26', '', 'Remorque', '', '526.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('5.27', '', 'Caravane', '', '527.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('5.28', '', 'Voiture d''habitation', '', '528.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('5.29', '', 'Motocycle', '', '529.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('5.30', '', 'Cyclomoteur', '', '530.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('5.31', '', 'Cycle', '', '531.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('5.32', '', 'Vélo tout-terrain', '', '532.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('5.33', '', 'Pousser le cycle', '', '533.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('5.34', '', 'Piéton', '', '534.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('5.35', '', 'Tramway ou chemin de fer routier', '', '535.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('5.36', '', 'Tracteur', '', '536.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('5.37', '', 'Char', '', '537.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('5.38', '', 'Dameuse de pistes', '', '538.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('5.39', '', 'Ski de fond', '', '539.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('5.40', '', 'Skier', '', '540.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('5.41', '', 'Luge', '', '541.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('5.50', '', 'Avion/Aérodrome', '', '550.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('5.51', '', 'Quai de chargement pour le transport sur rail', '', '551.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('5.52', '', 'Quai de chargement pour le transport sur un bac', '', '552.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('5.53', '', 'Zone industrielle et artisanale', '', '553.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('5.54', '', 'Passage en douane avec dédouanement à vue', '', '554.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('5.56', '', 'Hôpital avec service d''urgence', '', '556.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('5.57', '', 'Téléphone de secours', '', '557.svg');
INSERT INTO siro_vl.official_sign (id, value_en, value_fr, value_de, img) VALUES ('5.58', '', 'Extincteur', '', '558.svg');

