


CREATE TABLE siro_vl.status
(
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  active boolean default true,
  value_en text,
  value_fr text,
  value_de text
);

INSERT INTO siro_vl.status (id, value_en, value_fr, value_de) VALUES (1, 'unknown', 'inconnu', 'unknown');
INSERT INTO siro_vl.status (id, active, value_en, value_fr, value_de) VALUES (2, false, 'other', 'autre', 'other');
INSERT INTO siro_vl.status (id, value_en, value_fr, value_de) VALUES (3, 'to be determined', 'à déterminer', 'to be determined');

INSERT INTO siro_vl.status (id, value_en, value_fr, value_de) VALUES (10, 'ok', 'en état', 'ok');
INSERT INTO siro_vl.status (id, value_en, value_fr, value_de) VALUES (11, 'damaged', 'endommagé', 'damaged');
INSERT INTO siro_vl.status (id, value_en, value_fr, value_de) VALUES (12, 'broken', 'détruit', 'broken');
