DELETE FROM signalo_db.vl_support_base_type where id = 16 and value_fr = 'SPCH-Type 3';
DELETE FROM signalo_db.vl_support_base_type where id = 17 and value_fr = 'SPCH-Type 4';
DELETE FROM signalo_db.vl_support_base_type where id = 18 and value_fr = 'SPCH-Type 5';
DELETE FROM signalo_db.vl_support_base_type where id = 19 and value_fr = 'SPCH-Type 6';
DELETE FROM signalo_db.vl_support_base_type where id = 20 and value_fr = 'OFROU-Type A';
DELETE FROM signalo_db.vl_support_base_type where id = 21 and value_fr = 'OFROU-Type B';
DELETE FROM signalo_db.vl_support_base_type where id = 22 and value_fr = 'OFROU-Type C';
DELETE FROM signalo_db.vl_support_base_type where id = 23 and value_fr = 'OFROU-Type D';
DELETE FROM signalo_db.vl_support_base_type where id = 24 and value_fr = 'OFROU-Type E';
DELETE FROM signalo_db.vl_support_base_type where id = 25 and value_fr = 'OFROU-Type F';
DELETE FROM signalo_db.vl_support_base_type where id = 26 and value_fr = 'OFROU-Type 100';
DELETE FROM signalo_db.vl_support_base_type where id = 27 and value_fr = 'OFROU-Type 150';
DELETE FROM signalo_db.vl_support_base_type where id = 28 and value_fr = 'OFROU-Type 200';
DELETE FROM signalo_db.vl_support_base_type where id = 29 and value_fr = 'OFROU-Type 250';
DELETE FROM signalo_db.vl_support_base_type where id = 30 and value_fr = 'OFROU-Type 300';
DELETE FROM signalo_db.vl_support_base_type where id = 31 and value_fr = 'OFROU-Type 300 DS';
