-- 4.50.1 
INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.50.1-1', true, 'Wegweiser für Fahrräder und Motorfahrräder (1 Linie)', 'Indicateur de direction pour cycles et cyclomoteurs (1 ligne)', 'Indicatore di direzione per velocipedi e ciclomotori (1 linea)', NULL, NULL, NULL, NULL, NULL, '450-1-1-l.svg', '450-1-1-l.svg', '450-1-1-l.svg', '450-1-1-l.svg', 32, 167, 1, 'Bellinzona', NULL, NULL, NULL, true, '450-1-1-r.svg', '450-1-1-r.svg', '450-1-1-r.svg', '450-1-1-r.svg');

INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.50.1-2', true, 'Wegweiser für Fahrräder und Motorfahrräder (2 Linien)', 'Indicateur de direction pour cycles et cyclomoteurs (2 lignes)', 'Indicatore di direzione per velocipedi e ciclomotori (2 linee)', NULL, NULL, NULL, NULL, NULL, '450-1-2-l.svg', '450-1-2-l.svg', '450-1-2-l.svg', '450-1-2-l.svg', 42, 167, 2, 'Bellinzona  7km', 'Locarno 21km', NULL, NULL, true, '450-1-2-r.svg', '450-1-2-r.svg', '450-1-2-r.svg', '450-1-2-r.svg');

INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.50.1a-1', true, 'Wegweiser für Fahrräder und Motorfahrräder (1 Linie) mit Angabe der Route', 'Indicateur de direction pour cycles et cyclomoteurs (1 ligne) avec indication de l''itinéraire', 'Indicatore di direzione per velocipedi e ciclomotori (1 linea) con l''indicazione del percorso', NULL, NULL, NULL, NULL, NULL, '450-1a-1-l.svg', '450-1a-1-l.svg', '450-1a-1-l.svg', '450-1a-1-l.svg', 32, 189, 2, '3', 'Bellinzona  7km', NULL, NULL, true, '450-1a-1-r.svg', '450-1a-1-r.svg', '450-1a-1-r.svg', '450-1a-1-r.svg');

-- 4.51.1
INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.1', true, 'Wegweiser ohne Zielangabe (Fahrrad)', 'Indicateur de direction sans mention de la destination (vélo)', 'Indicatore di direzione senza indicazione della destinazione (bicicletta)', NULL, NULL, NULL, NULL, NULL, '451-1-vel-l.svg', '451-1-vel-l.svg', '451-1-vel-l.svg', '451-1-vel-l.svg', 32, 85, 0, NULL, NULL, NULL, NULL, true, '451-1-vel-r.svg', '451-1-vel-r.svg', '451-1-vel-r.svg', '451-1-vel-r.svg');

INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.1a', true, 'Wegweiser ohne Zielangabe (Fahrrad) mit Angabe der Route', 'Indicateur de direction sans mention de la destination (vélo) avec indication de l''itinéraire', 'Indicatore di direzione senza indicazione della destinazione (bicicletta) con l''indicazione del percorso', NULL, NULL, NULL, NULL, NULL, '451-1a-vel-l.svg', '451-1a-vel-l.svg', '451-1a-vel-l.svg', '451-1a-vel-l.svg', 32, 85, 0, NULL, NULL, NULL, NULL, true, '451-1a-vel-r.svg', '451-1a-vel-r.svg', '451-1a-vel-r.svg', '451-1a-vel-r.svg');

-- 4.51.2
INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.2-vel', true, 'Vorwegweiser ohne Zielangabe (Fahrrad) - geradeaus', 'Indicateur de direction avancé sans mention de la destination (vélo) - tout droit', 'Segnale di preavviso senza destinazione (bicicletta) - dritto', NULL, NULL, NULL, NULL, NULL, '451-2-vel.svg', '451-2-vel.svg', '451-2-vel.svg', '451-2-vel.svg', 48, 32, 0, NULL, NULL, NULL, NULL, false, '451-2-vel.svg', '451-2-vel.svg', '451-2-vel.svg', '451-2-vel.svg');

INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.2-vel-r', true, 'Vorwegweiser ohne Zielangabe (Fahrrad) - nach rechts', 'Indicateur de direction avancé sans mention de la destination (vélo) - à droite', 'Segnale di preavviso senza destinazione (bicicletta) - a destra', NULL, NULL, NULL, NULL, NULL, '451-2-vel-r.svg', '451-2-vel-r.svg', '451-2-vel-r.svg', '451-2-vel-r.svg', 48, 32, 0, NULL, NULL, NULL, NULL, false, '451-2-vel-r.svg', '451-2-vel-r.svg', '451-2-vel-r.svg', '451-2-vel-r.svg');

INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.2-vel-l', true, 'Vorwegweiser ohne Zielangabe (Fahrrad) - nach links', 'Indicateur de direction avancé sans mention de la destination (vélo) - à gauche', 'Segnale di preavviso senza destinazione (bicicletta) - a sinistra', NULL, NULL, NULL, NULL, NULL, '451-2-vel-l.svg', '451-2-vel-l.svg', '451-2-vel-l.svg', '451-2-vel-l.svg', 48, 32, 0, NULL, NULL, NULL, NULL, false, '451-2-vel-l.svg', '451-2-vel-l.svg', '451-2-vel-l.svg', '451-2-vel-l.svg');

INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.2a-vel', true, 'Vorwegweiser ohne Zielangabe (Fahrrad) - geradeaus, mit Angabe der Route', 'Indicateur de direction avancé sans mention de la destination (vélo) - tout droit, avec indication de l''itinéraire', 'Segnale di preavviso senza destinazione (bicicletta) - dritto,  con l''indicazione del percorso', NULL, NULL, NULL, NULL, NULL, '451-2a-vel.svg', '451-2a-vel.svg', '451-2a-vel.svg', '451-2a-vel.svg', 85, 32, 1, '5', NULL, NULL, NULL, false, '451-2a-vel.svg', '451-2a-vel.svg', '451-2a-vel.svg', '451-2a-vel.svg');

INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.2a-vel-r', true, 'Vorwegweiser ohne Zielangabe (Fahrrad) - nach rechts, mit Angabe der Route', 'Indicateur de direction avancé sans mention de la destination (vélo) - à droite, avec indication de l''itinéraire', 'Segnale di preavviso senza destinazione (bicicletta) - a destra, con l''indicazione del percorso', NULL, NULL, NULL, NULL, NULL, '451-2a-vel-r.svg', '451-2a-vel-r.svg', '451-2a-vel-r.svg', '451-2a-vel-r.svg', 85, 32, 1, '5', NULL, NULL, NULL, false, '451-2a-vel-r.svg', '451-2a-vel-r.svg', '451-2a-vel-r.svg', '451-2a-vel-r.svg');

INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.2a-vel-l', true, 'Vorwegweiser ohne Zielangabe (Fahrrad) - nach links, mit Angabe der Route', 'Indicateur de direction avancé sans mention de la destination (vélo) - à gauche, avec indication de l''itinéraire', 'Segnale di preavviso senza destinazione (bicicletta) - a sinistra, con l''indicazione del percorso', NULL, NULL, NULL, NULL, NULL, '451-2a-vel-l.svg', '451-2a-vel-l.svg', '451-2a-vel-l.svg', '451-2a-vel-l.svg', 85, 32, 1, '5', NULL, NULL, NULL, false, '451-2a-vel-l.svg', '451-2a-vel-l.svg', '451-2a-vel-l.svg', '451-2a-vel-l.svg');

INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.2b-vel', true, 'Vorwegweiser ohne Zielangabe (Fahrrad) - geradeaus, mit Angabe der Route, mit Distanzangabe', 'Indicateur de direction avancé sans mention de la destination (vélo) - tout droit, avec indication de l''itinéraire, avec indication de la distance', 'Segnale di preavviso senza destinazione (bicicletta) - dritto,  con l''indicazione del percorso, con l''indicazione della distanza', NULL, NULL, NULL, NULL, NULL, '451-2b-vel.svg', '451-2b-vel.svg', '451-2b-vel.svg', '451-2b-vel.svg', 94, 32, 2, '5', '80 m', NULL, NULL, false, '451-2b-vel.svg', '451-2b-vel.svg', '451-2b-vel.svg', '451-2b-vel.svg');

INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.2b-vel-r', true, 'Vorwegweiser ohne Zielangabe (Fahrrad) - nach rechts, mit Angabe der Route, mit Distanzangabe', 'Indicateur de direction avancé sans mention de la destination (vélo) - à droite, avec indication de l''itinéraire, avec indication de la distance', 'Segnale di preavviso senza destinazione (bicicletta) - a destra, con l''indicazione del percorso, con l''indicazione della distanza', NULL, NULL, NULL, NULL, NULL, '451-2b-vel-r.svg', '451-2b-vel-r.svg', '451-2b-vel-r.svg', '451-2b-vel-r.svg', 94, 32, 2, '5', '80 m', NULL, NULL, false, '451-2b-vel-r.svg', '451-2b-vel-r.svg', '451-2b-vel-r.svg', '451-2b-vel-r.svg');

INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.2b-vel-l', true, 'Vorwegweiser ohne Zielangabe (Fahrrad) - nach links, mit Angabe der Route, mit Distanzangabe', 'Indicateur de direction avancé sans mention de la destination (vélo) - à gauche, avec indication de l''itinéraire, avec indication de la distance', 'Segnale di preavviso senza destinazione (bicicletta) - a sinistra, con l''indicazione del percorso, con l''indicazione della distanza', NULL, NULL, NULL, NULL, NULL, '451-2b-vel-l.svg', '451-2b-vel-l.svg', '451-2b-vel-l.svg', '451-2b-vel-l.svg', 94, 32, 2, '5', '80 m', NULL, NULL, false, '451-2b-vel-l.svg', '451-2b-vel-l.svg', '451-2b-vel-l.svg', '451-2b-vel-l.svg');


-- 4.51.3
INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.3-vel', true, 'Bestätigungstafel (Fahrrad)', 'Plaque de confirmation (vélo)', 'Cartello di conferma (bicicletta)', NULL, NULL, NULL, NULL, NULL, '451-3-vel.svg', '451-3-vel.svg', '451-3-vel.svg', '451-3-vel.svg', 32, 32, 0, NULL, NULL, NULL, NULL, false, '451-3-vel.svg', '451-3-vel.svg', '451-3-vel.svg', '451-3-vel.svg');

INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.3a-vel', true, 'Bestätigungstafel (Fahrrad) mit Angabe der Route', 'Plaque de confirmation (vélo) avec indication de l''itinéraire', 'Cartello di conferma (bicicletta) con l''indicazione del percorso', NULL, NULL, NULL, NULL, NULL, '451-3a-vel.svg', '451-3a-vel.svg', '451-3a-vel.svg', '451-3a-vel.svg', 48, 32, 1, '3', NULL, NULL, NULL, false, '451-3a-vel.svg', '451-3a-vel.svg', '451-3a-vel.svg', '451-3a-vel.svg');

INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.3-mtb', true, 'Bestätigungstafel (Mountainbike)', 'Plaque de confirmation (VTT)', 'Cartello di conferma (mountain bike)', NULL, NULL, NULL, NULL, NULL, '451-3-mtb.svg', '451-3-mtb.svg', '451-3-mtb.svg', '451-3-mtb.svg', 32, 32, 0, NULL, NULL, NULL, NULL, false, '451-3-mtb.svg', '451-3-mtb.svg', '451-3-mtb.svg', '451-3-mtb.svg');

INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.3a-mtb', true, 'Bestätigungstafel (Mountainbike) mit Angabe der Route', 'Plaque de confirmation (VTT) avec indication de l''itinéraire', 'Cartello di conferma (mountain bike) con l''indicazione del percorso', NULL, NULL, NULL, NULL, NULL, '451-3a-mtb.svg', '451-3a-mtb.svg', '451-3a-mtb.svg', '451-3a-mtb.svg', 48, 32, 1, '44', NULL, NULL, NULL, false, '451-3a-mtb.svg', '451-3a-mtb.svg', '451-3a-mtb.svg', '451-3a-mtb.svg');

INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.3-vel-mtb', true, 'Bestätigungstafel (Fahrrad, Mountainbike)', 'Plaque de confirmation (vélo, VTT)', 'Cartello di conferma (bicicletta, mountain bike)', NULL, NULL, NULL, NULL, NULL, '451-3-vel-mtb.svg', '451-3-vel-mtb.svg', '451-3-vel-mtb.svg', '451-3-vel-mtb.svg', 48, 32, 0, NULL, NULL, NULL, NULL, false, '451-3-vel-mtb.svg', '451-3-vel-mtb.svg', '451-3-vel-mtb.svg', '451-3-vel-mtb.svg');

-- delete old signs ?
DELETE FROM signalo_db.vl_official_sign WHERE id = '4.51.1-a';
DELETE FROM signalo_db.vl_official_sign WHERE id = '4.51.1-b';