-- 4.50.3 
INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.50.3-1', true, 'Wegweiser für Mountainbikes (1 Linie)', 'Indicateur de direction pour VTT (1 ligne)', 'Indicatore di direzione per mountain bike (1 linea)', NULL, NULL, NULL, NULL, NULL, '450-3-1-l.svg', '450-3-1-l.svg', '450-3-1-l.svg', '450-3-1-l.svg', 32, 167, 1, 'Solothurn', NULL, NULL, NULL, true, '450-3-1-r.svg', '450-3-1-r.svg', '450-3-1-r.svg', '450-3-1-r.svg');

INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.50.3-2', true, 'Wegweiser für Mountainbikes (2 Linien)', 'Indicateur de direction pour VTT (2 lignes)', 'Indicatore di direzione per mountain bike (2 linee)', NULL, NULL, NULL, NULL, NULL, '450-3-2-l.svg', '450-3-2-l.svg', '450-3-2-l.svg', '450-3-2-l.svg', 42, 167, 2, 'Solothurn', 'Oensingen', NULL, NULL, true, '450-3-2-r.svg', '450-3-2-r.svg', '450-3-2-r.svg', '450-3-2-r.svg');

INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.50.3a-1', true, 'Wegweiser für Mountainbikes (1 Linie) mit Angabe der Route', 'Indicateur de direction pour VTT (1 ligne) avec indication de l''itinéraire', 'Indicatore di direzione per mountain bike (1 linea) con l''indicazione del percorso', NULL, NULL, NULL, NULL, NULL, '450-3a-1-l.svg', '450-3a-1-l.svg', '450-3a-1-l.svg', '450-3a-1-l.svg', 32, 189, 2, '3', 'Solothurn', NULL, NULL, true, '450-3a-1-r.svg', '450-3a-1-r.svg', '450-3a-1-r.svg', '450-3a-1-r.svg');

INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.50.3a-2', true, 'Wegweiser für Mountainbikes (2 Linien) mit Angabe der Route', 'Indicateur de direction pour VTT (2 lignes) avec indication de l''itinéraire', 'Indicatore di direzione per mountain bike (2 linee) con l''indicazione del percorso', NULL, NULL, NULL, NULL, NULL, '450-3a-2-l.svg', '450-3a-2-l.svg', '450-3a-2-l.svg', '450-3a-2-l.svg', 42, 189, 2, '3', 'Solothurn', 'Oensingen', NULL, true, '450-3a-2-r.svg', '450-3a-2-r.svg', '450-3a-2-r.svg', '450-3a-2-r.svg');

-- 4.50.4
INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.50.4-1', true, 'Wegweiser für fahrzeugähnliche Geräte (1 Linie)', 'Indicateur de direction pour engins assimilés à des véhicules (1 ligne)', 'Indicatore di direzione per mezzi simili a veicoli (1 linea)', NULL, NULL, NULL, NULL, NULL, '450-4-1-l.svg', '450-4-1-l.svg', '450-4-1-l.svg', '450-4-1-l.svg', 32, 167, 1, 'Solothurn', NULL, NULL, NULL, true, '450-4-1-r.svg', '450-4-1-r.svg', '450-4-1-r.svg', '450-4-1-r.svg');

INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.50.4-2', true, 'Wegweiser für fahrzeugähnliche Geräte (2 Linien)', 'Indicateur de direction pour engins assimilés à des véhicules (2 lignes)', 'Indicatore di direzione per mezzi simili a veicoli (2 linee)', NULL, NULL, NULL, NULL, NULL, '450-4-2-l.svg', '450-4-2-l.svg', '450-4-2-l.svg', '450-4-2-l.svg', 42, 167, 2, 'Solothurn', 'Oensingen', NULL, NULL, true, '450-4-2-r.svg', '450-4-2-r.svg', '450-4-2-r.svg', '450-4-2-r.svg');

INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.50.4a-1', true, 'Wegweiser für fahrzeugähnliche Geräte (1 Linie) mit Angabe der Route', 'Indicateur de direction pour engins assimilés à des véhicules (1 ligne) avec indication de l''itinéraire', 'Indicatore di direzione per mezzi simili a veicoli (1 linea) con l''indicazione del percorso', NULL, NULL, NULL, NULL, NULL, '450-4a-1-l.svg', '450-4a-1-l.svg', '450-4a-1-l.svg', '450-4a-1-l.svg', 32, 189, 2, '3', 'Solothurn', NULL, NULL, true, '450-4a-1-r.svg', '450-4a-1-r.svg', '450-4a-1-r.svg', '450-4a-1-r.svg');

INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.50.4a-2', true, 'Wegweiser für fahrzeugähnliche Geräte (2 Linien) mit Angabe der Route', 'Indicateur de direction pour engins assimilés à des véhicules (2 lignes) avec indication de l''itinéraire', 'Indicatore di direzione per mezzi simili a veicoli (2 linee) con l''indicazione del percorso', NULL, NULL, NULL, NULL, NULL, '450-4a-2-l.svg', '450-4a-2-l.svg', '450-4a-2-l.svg', '450-4a-2-l.svg', 42, 189, 2, '3', 'Solothurn', 'Oensingen', NULL, true, '450-4a-2-r.svg', '450-4a-2-r.svg', '450-4a-2-r.svg', '450-4a-2-r.svg');

-- 4.51.1
INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.1-mtb', true, 'Wegweiser ohne Zielangabe (Mountainbike)', 'Indicateur de direction sans mention de la destination (VTT)', 'Indicatore di direzione senza indicazione della destinazione (mountain bike)', NULL, NULL, NULL, NULL, NULL, '451-1-mtb-l.svg', '451-1-mtb-l.svg', '451-1-mtb-l.svg', '451-1-mtb-l.svg', 32, 85, 0, NULL, NULL, NULL, NULL, true, '451-1-mtb-r.svg', '451-1-mtb-r.svg', '451-1-mtb-r.svg', '451-1-mtb-r.svg');

INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.1a-mtb', true, 'Wegweiser ohne Zielangabe (Mountainbike) mit Angabe der Route', 'Indicateur de direction sans mention de la destination (VTT) avec indication de l''itinéraire', 'Indicatore di direzione senza indicazione della destinazione (mountain bike) con l''indicazione del percorso', NULL, NULL, NULL, NULL, NULL, '451-1a-mtb-l.svg', '451-1a-mtb-l.svg', '451-1a-mtb-l.svg', '451-1a-mtb-l.svg', 32, 85, 0, NULL, NULL, NULL, NULL, true, '451-1a-mtb-r.svg', '451-1a-mtb-r.svg', '451-1a-mtb-r.svg', '451-1a-mtb-r.svg');

INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.1-roll', true, 'Wegweiser ohne Zielangabe (fahrzeugähnliche Geräte)', 'Indicateur de direction sans mention de la destination (engins assimilés à des véhicules)', 'Indicatore di direzione senza indicazione della destinazione (mezzi simili a veicoli)', NULL, NULL, NULL, NULL, NULL, '451-1-roll-l.svg', '451-1-roll-l.svg', '451-1-roll-l.svg', '451-1-roll-l.svg', 32, 85, 0, NULL, NULL, NULL, NULL, true, '451-1-roll-r.svg', '451-1-roll-r.svg', '451-1-roll-r.svg', '451-1-roll-r.svg');

INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.1a-roll', true, 'Wegweiser ohne Zielangabe (fahrzeugähnliche Geräte) mit Angabe der Route', 'Indicateur de direction sans mention de la destination (engins assimilés à des véhicules) avec indication de l''itinéraire', 'Indicatore di direzione senza indicazione della destinazione (mezzi simili a veicoli) con l''indicazione del percorso', NULL, NULL, NULL, NULL, NULL, '451-1a-roll-l.svg', '451-1a-roll-l.svg', '451-1a-roll-l.svg', '451-1a-roll-l.svg', 32, 85, 0, NULL, NULL, NULL, NULL, true, '451-1a-roll-r.svg', '451-1a-roll-r.svg', '451-1a-roll-r.svg', '451-1a-roll-r.svg');

-- 4.51.2 mtb
INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.2-mtb', true, 'Vorwegweiser ohne Zielangabe (Mountainbike) - geradeaus', 'Indicateur de direction avancé sans mention de la destination (VTT) - tout droit', 'Segnale di preavviso senza destinazione (mountain bike) - dritto', NULL, NULL, NULL, NULL, NULL, '451-2-mtb.svg', '451-2-mtb.svg', '451-2-mtb.svg', '451-2-mtb.svg', 48, 32, 0, NULL, NULL, NULL, NULL, false, '451-2-mtb.svg', '451-2-mtb.svg', '451-2-mtb.svg', '451-2-mtb.svg');

INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.2-mtb-r', true, 'Vorwegweiser ohne Zielangabe (Mountainbike) - nach rechts', 'Indicateur de direction avancé sans mention de la destination (VTT) - à droite', 'Segnale di preavviso senza destinazione (mountain bike) - a destra', NULL, NULL, NULL, NULL, NULL, '451-2-mtb-r.svg', '451-2-mtb-r.svg', '451-2-mtb-r.svg', '451-2-mtb-r.svg', 48, 32, 0, NULL, NULL, NULL, NULL, false, '451-2-mtb-r.svg', '451-2-mtb-r.svg', '451-2-mtb-r.svg', '451-2-mtb-r.svg');

INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.2-mtb-l', true, 'Vorwegweiser ohne Zielangabe (Mountainbike) - nach links', 'Indicateur de direction avancé sans mention de la destination (VTT) - à gauche', 'Segnale di preavviso senza destinazione (mountain bike) - a sinistra', NULL, NULL, NULL, NULL, NULL, '451-2-mtb-l.svg', '451-2-mtb-l.svg', '451-2-mtb-l.svg', '451-2-mtb-l.svg', 48, 32, 0, NULL, NULL, NULL, NULL, false, '451-2-mtb-l.svg', '451-2-mtb-l.svg', '451-2-mtb-l.svg', '451-2-mtb-l.svg');


-- half right / half left (obliques)
INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.2-mtb-hr', true, 'Vorwegweiser ohne Zielangabe (Mountainbike) - nach halb-rechts', 'Indicateur de direction avancé sans mention de la destination (VTT) - légèrement à droite', 'Segnale di preavviso senza destinazione (mountain bike) - mezzo a destra', NULL, NULL, NULL, NULL, NULL, '451-2-mtb-hr.svg', '451-2-mtb-hr.svg', '451-2-mtb-hr.svg', '451-2-mtb-hr.svg', 48, 32, 0, NULL, NULL, NULL, NULL, false, '451-2-mtb-hr.svg', '451-2-mtb-hr.svg', '451-2-mtb-hr.svg', '451-2-mtb-hr.svg');

INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.2-mtb-hl', true, 'Vorwegweiser ohne Zielangabe (Mountainbike) - nach halb-links', 'Indicateur de direction avancé sans mention de la destination (VTT) - légèrement à gauche', 'Segnale di preavviso senza destinazione (mountain bike) - mezzo a sinistra', NULL, NULL, NULL, NULL, NULL, '451-2-mtb-hl.svg', '451-2-mtb-hl.svg', '451-2-mtb-hl.svg', '451-2-mtb-hl.svg', 48, 32, 0, NULL, NULL, NULL, NULL, false, '451-2-mtb-hl.svg', '451-2-mtb-hl.svg', '451-2-mtb-hl.svg', '451-2-mtb-hl.svg');
--

INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.2a-mtb', true, 'Vorwegweiser ohne Zielangabe (Mountainbike) - geradeaus, mit Angabe der Route', 'Indicateur de direction avancé sans mention de la destination (VTT) - tout droit, avec indication de l''itinéraire', 'Segnale di preavviso senza destinazione (mountain bike) - dritto,  con l''indicazione del percorso', NULL, NULL, NULL, NULL, NULL, '451-2a-mtb.svg', '451-2a-mtb.svg', '451-2a-mtb.svg', '451-2a-mtb.svg', 85, 32, 1, '5', NULL, NULL, NULL, false, '451-2a-mtb.svg', '451-2a-mtb.svg', '451-2a-mtb.svg', '451-2a-mtb.svg');

INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.2a-mtb-r', true, 'Vorwegweiser ohne Zielangabe (Mountainbike) - nach rechts, mit Angabe der Route', 'Indicateur de direction avancé sans mention de la destination (VTT) - à droite, avec indication de l''itinéraire', 'Segnale di preavviso senza destinazione (mountain bike) - a destra, con l''indicazione del percorso', NULL, NULL, NULL, NULL, NULL, '451-2a-mtb-r.svg', '451-2a-mtb-r.svg', '451-2a-mtb-r.svg', '451-2a-mtb-r.svg', 85, 32, 1, '5', NULL, NULL, NULL, false, '451-2a-mtb-r.svg', '451-2a-mtb-r.svg', '451-2a-mtb-r.svg', '451-2a-mtb-r.svg');

INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.2a-mtb-l', true, 'Vorwegweiser ohne Zielangabe (Mountainbike) - nach links, mit Angabe der Route', 'Indicateur de direction avancé sans mention de la destination (VTT) - à gauche, avec indication de l''itinéraire', 'Segnale di preavviso senza destinazione (mountain bike) - a sinistra, con l''indicazione del percorso', NULL, NULL, NULL, NULL, NULL, '451-2a-mtb-l.svg', '451-2a-mtb-l.svg', '451-2a-mtb-l.svg', '451-2a-mtb-l.svg', 85, 32, 1, '5', NULL, NULL, NULL, false, '451-2a-mtb-l.svg', '451-2a-mtb-l.svg', '451-2a-mtb-l.svg', '451-2a-mtb-l.svg');

-- half right / half left (obliques)
INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.2a-mtb-hr', true, 'Vorwegweiser ohne Zielangabe (Mountainbike) - nach halb-rechts, mit Angabe der Route', 'Indicateur de direction avancé sans mention de la destination (VTT) - légèrement à droite, avec indication de l''itinéraire', 'Segnale di preavviso senza destinazione (mountain bike) - mezzo a destra, con l''indicazione del percorso', NULL, NULL, NULL, NULL, NULL, '451-2a-mtb-hr.svg', '451-2a-mtb-hr.svg', '451-2a-mtb-hr.svg', '451-2a-mtb-hr.svg', 85, 32, 1, '5', NULL, NULL, NULL, false, '451-2a-mtb-hr.svg', '451-2a-mtb-hr.svg', '451-2a-mtb-hr.svg', '451-2a-mtb-hr.svg');

INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.2a-mtb-hl', true, 'Vorwegweiser ohne Zielangabe (Mountainbike) - nach halb-links, mit Angabe der Route', 'Indicateur de direction avancé sans mention de la destination (VTT) - légèrement à gauche, avec indication de l''itinéraire', 'Segnale di preavviso senza destinazione (mountain bike) - mezzo a sinistra, con l''indicazione del percorso', NULL, NULL, NULL, NULL, NULL, '451-2a-mtb-hl.svg', '451-2a-mtb-hl.svg', '451-2a-mtb-hl.svg', '451-2a-mtb-hl.svg', 85, 32, 1, '5', NULL, NULL, NULL, false, '451-2a-mtb-hl.svg', '451-2a-mtb-hl.svg', '451-2a-mtb-hl.svg', '451-2a-mtb-hl.svg');
--

INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.2b-mtb', true, 'Vorwegweiser ohne Zielangabe (Mountainbike) - geradeaus, mit Angabe der Route, mit Distanzangabe', 'Indicateur de direction avancé sans mention de la destination (VTT) - tout droit, avec indication de l''itinéraire, avec indication de la distance', 'Segnale di preavviso senza destinazione (mountain bike) - dritto,  con l''indicazione del percorso, con l''indicazione della distanza', NULL, NULL, NULL, NULL, NULL, '451-2b-mtb.svg', '451-2b-mtb.svg', '451-2b-mtb.svg', '451-2b-mtb.svg', 94, 32, 2, '5', '80 m', NULL, NULL, false, '451-2b-mtb.svg', '451-2b-mtb.svg', '451-2b-mtb.svg', '451-2b-mtb.svg');

INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.2b-mtb-r', true, 'Vorwegweiser ohne Zielangabe (Mountainbike) - nach rechts, mit Angabe der Route, mit Distanzangabe', 'Indicateur de direction avancé sans mention de la destination (VTT) - à droite, avec indication de l''itinéraire, avec indication de la distance', 'Segnale di preavviso senza destinazione (mountain bike) - a destra, con l''indicazione del percorso, con l''indicazione della distanza', NULL, NULL, NULL, NULL, NULL, '451-2b-mtb-r.svg', '451-2b-mtb-r.svg', '451-2b-mtb-r.svg', '451-2b-mtb-r.svg', 94, 32, 2, '5', '80 m', NULL, NULL, false, '451-2b-mtb-r.svg', '451-2b-mtb-r.svg', '451-2b-mtb-r.svg', '451-2b-mtb-r.svg');

INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.2b-mtb-l', true, 'Vorwegweiser ohne Zielangabe (Mountainbike) - nach links, mit Angabe der Route, mit Distanzangabe', 'Indicateur de direction avancé sans mention de la destination (VTT) - à gauche, avec indication de l''itinéraire, avec indication de la distance', 'Segnale di preavviso senza destinazione (mountain bike) - a sinistra, con l''indicazione del percorso, con l''indicazione della distanza', NULL, NULL, NULL, NULL, NULL, '451-2b-mtb-l.svg', '451-2b-mtb-l.svg', '451-2b-mtb-l.svg', '451-2b-mtb-l.svg', 94, 32, 2, '5', '80 m', NULL, NULL, false, '451-2b-mtb-l.svg', '451-2b-mtb-l.svg', '451-2b-mtb-l.svg', '451-2b-mtb-l.svg');

-- half right / half left (obliques)
INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.2b-mtb-hr', true, 'Vorwegweiser ohne Zielangabe (Mountainbike) - nach halb-rechts, mit Angabe der Route, mit Distanzangabe', 'Indicateur de direction avancé sans mention de la destination (VTT) - légèrement à droite, avec indication de l''itinéraire, avec indication de la distance', 'Segnale di preavviso senza destinazione (mountain bike) - mezzo a destra, con l''indicazione del percorso, con l''indicazione della distanza', NULL, NULL, NULL, NULL, NULL, '451-2b-mtb-hr.svg', '451-2b-mtb-hr.svg', '451-2b-mtb-hr.svg', '451-2b-mtb-hr.svg', 94, 32, 2, '5', '80 m', NULL, NULL, false, '451-2b-mtb-hr.svg', '451-2b-mtb-hr.svg', '451-2b-mtb-hr.svg', '451-2b-mtb-hr.svg');

INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.2b-mtb-hl', true, 'Vorwegweiser ohne Zielangabe (Mountainbike) - nach halb-links, mit Angabe der Route, mit Distanzangabe', 'Indicateur de direction avancé sans mention de la destination (VTT) - légèrement à gauche, avec indication de l''itinéraire, avec indication de la distance', 'Segnale di preavviso senza destinazione (mountain bike) - mezzo a sinistra, con l''indicazione del percorso, con l''indicazione della distanza', NULL, NULL, NULL, NULL, NULL, '451-2b-mtb-hl.svg', '451-2b-mtb-hl.svg', '451-2b-mtb-hl.svg', '451-2b-mtb-hl.svg', 94, 32, 2, '5', '80 m', NULL, NULL, false, '451-2b-mtb-hl.svg', '451-2b-mtb-hl.svg', '451-2b-mtb-hl.svg', '451-2b-mtb-hl.svg');



-- 4.51.2 roller
INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.2-roll', true, 'Vorwegweiser ohne Zielangabe (fahrzeugähnliche Geräte) - geradeaus', 'Indicateur de direction avancé sans mention de la destination (engins assimilés à des véhicules) - tout droit', 'Segnale di preavviso senza destinazione (mezzi simili a veicoli) - dritto', NULL, NULL, NULL, NULL, NULL, '451-2-roll.svg', '451-2-roll.svg', '451-2-roll.svg', '451-2-roll.svg', 48, 32, 0, NULL, NULL, NULL, NULL, false, '451-2-roll.svg', '451-2-roll.svg', '451-2-roll.svg', '451-2-roll.svg');

INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.2-roll-r', true, 'Vorwegweiser ohne Zielangabe (fahrzeugähnliche Geräte) - nach rechts', 'Indicateur de direction avancé sans mention de la destination (engins assimilés à des véhicules) - à droite', 'Segnale di preavviso senza destinazione (mezzi simili a veicoli) - a destra', NULL, NULL, NULL, NULL, NULL, '451-2-roll-r.svg', '451-2-roll-r.svg', '451-2-roll-r.svg', '451-2-roll-r.svg', 48, 32, 0, NULL, NULL, NULL, NULL, false, '451-2-roll-r.svg', '451-2-roll-r.svg', '451-2-roll-r.svg', '451-2-roll-r.svg');

INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.2-roll-l', true, 'Vorwegweiser ohne Zielangabe (fahrzeugähnliche Geräte) - nach links', 'Indicateur de direction avancé sans mention de la destination (engins assimilés à des véhicules) - à gauche', 'Segnale di preavviso senza destinazione (mezzi simili a veicoli) - a sinistra', NULL, NULL, NULL, NULL, NULL, '451-2-roll-l.svg', '451-2-roll-l.svg', '451-2-roll-l.svg', '451-2-roll-l.svg', 48, 32, 0, NULL, NULL, NULL, NULL, false, '451-2-roll-l.svg', '451-2-roll-l.svg', '451-2-roll-l.svg', '451-2-roll-l.svg');

-- half right / half left (obliques)
INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.2-roll-hr', true, 'Vorwegweiser ohne Zielangabe (fahrzeugähnliche Geräte) - nach halb-rechts', 'Indicateur de direction avancé sans mention de la destination (engins assimilés à des véhicules) - légèrement à droite', 'Segnale di preavviso senza destinazione (mezzi simili a veicoli) - mezzo a destra', NULL, NULL, NULL, NULL, NULL, '451-2-roll-hr.svg', '451-2-roll-hr.svg', '451-2-roll-hr.svg', '451-2-roll-hr.svg', 48, 32, 0, NULL, NULL, NULL, NULL, false, '451-2-roll-hr.svg', '451-2-roll-hr.svg', '451-2-roll-hr.svg', '451-2-roll-hr.svg');

INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.2-roll-hl', true, 'Vorwegweiser ohne Zielangabe (fahrzeugähnliche Geräte) - nach halb-links', 'Indicateur de direction avancé sans mention de la destination (engins assimilés à des véhicules) - légèrement à gauche', 'Segnale di preavviso senza destinazione (mezzi simili a veicoli) - mezzo a sinistra', NULL, NULL, NULL, NULL, NULL, '451-2-roll-hl.svg', '451-2-roll-hl.svg', '451-2-roll-hl.svg', '451-2-roll-hl.svg', 48, 32, 0, NULL, NULL, NULL, NULL, false, '451-2-roll-hl.svg', '451-2-roll-hl.svg', '451-2-roll-hl.svg', '451-2-roll-hl.svg');
--


INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.2a-roll', true, 'Vorwegweiser ohne Zielangabe (fahrzeugähnliche Geräte) - geradeaus, mit Angabe der Route', 'Indicateur de direction avancé sans mention de la destination (engins assimilés à des véhicules) - tout droit, avec indication de l''itinéraire', 'Segnale di preavviso senza destinazione (mezzi simili a veicoli) - dritto,  con l''indicazione del percorso', NULL, NULL, NULL, NULL, NULL, '451-2a-roll.svg', '451-2a-roll.svg', '451-2a-roll.svg', '451-2a-roll.svg', 85, 32, 1, '5', NULL, NULL, NULL, false, '451-2a-roll.svg', '451-2a-roll.svg', '451-2a-roll.svg', '451-2a-roll.svg');

INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.2a-roll-r', true, 'Vorwegweiser ohne Zielangabe (fahrzeugähnliche Geräte) - nach rechts, mit Angabe der Route', 'Indicateur de direction avancé sans mention de la destination (engins assimilés à des véhicules) - à droite, avec indication de l''itinéraire', 'Segnale di preavviso senza destinazione (mezzi simili a veicoli) - a destra, con l''indicazione del percorso', NULL, NULL, NULL, NULL, NULL, '451-2a-roll-r.svg', '451-2a-roll-r.svg', '451-2a-roll-r.svg', '451-2a-roll-r.svg', 85, 32, 1, '5', NULL, NULL, NULL, false, '451-2a-roll-r.svg', '451-2a-roll-r.svg', '451-2a-roll-r.svg', '451-2a-roll-r.svg');

INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.2a-roll-l', true, 'Vorwegweiser ohne Zielangabe (fahrzeugähnliche Geräte) - nach links, mit Angabe der Route', 'Indicateur de direction avancé sans mention de la destination (engins assimilés à des véhicules) - à gauche, avec indication de l''itinéraire', 'Segnale di preavviso senza destinazione (mezzi simili a veicoli) - a sinistra, con l''indicazione del percorso', NULL, NULL, NULL, NULL, NULL, '451-2a-roll-l.svg', '451-2a-roll-l.svg', '451-2a-roll-l.svg', '451-2a-roll-l.svg', 85, 32, 1, '5', NULL, NULL, NULL, false, '451-2a-roll-l.svg', '451-2a-roll-l.svg', '451-2a-roll-l.svg', '451-2a-roll-l.svg');

-- half right / half left (obliques)
INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.2a-roll-hr', true, 'Vorwegweiser ohne Zielangabe (fahrzeugähnliche Geräte) - nach halb-rechts, mit Angabe der Route', 'Indicateur de direction avancé sans mention de la destination (engins assimilés à des véhicules) - légèrement à droite, avec indication de l''itinéraire', 'Segnale di preavviso senza destinazione (mezzi simili a veicoli) - mezzo a destra, con l''indicazione del percorso', NULL, NULL, NULL, NULL, NULL, '451-2a-roll-hr.svg', '451-2a-roll-hr.svg', '451-2a-roll-hr.svg', '451-2a-roll-hr.svg', 85, 32, 1, '5', NULL, NULL, NULL, false, '451-2a-roll-hr.svg', '451-2a-roll-hr.svg', '451-2a-roll-hr.svg', '451-2a-roll-hr.svg');

INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.2a-roll-hl', true, 'Vorwegweiser ohne Zielangabe (fahrzeugähnliche Geräte) - nach halb-links, mit Angabe der Route', 'Indicateur de direction avancé sans mention de la destination (engins assimilés à des véhicules) - légèrement à gauche, avec indication de l''itinéraire', 'Segnale di preavviso senza destinazione (mezzi simili a veicoli) - mezzo a sinistra, con l''indicazione del percorso', NULL, NULL, NULL, NULL, NULL, '451-2a-roll-hl.svg', '451-2a-roll-hl.svg', '451-2a-roll-hl.svg', '451-2a-roll-hl.svg', 85, 32, 1, '5', NULL, NULL, NULL, false, '451-2a-roll-hl.svg', '451-2a-roll-hl.svg', '451-2a-roll-hl.svg', '451-2a-roll-hl.svg');
--


INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.2b-roll', true, 'Vorwegweiser ohne Zielangabe (fahrzeugähnliche Geräte) - geradeaus, mit Angabe der Route, mit Distanzangabe', 'Indicateur de direction avancé sans mention de la destination (engins assimilés à des véhicules) - tout droit, avec indication de l''itinéraire, avec indication de la distance', 'Segnale di preavviso senza destinazione (mezzi simili a veicoli) - dritto,  con l''indicazione del percorso, con l''indicazione della distanza', NULL, NULL, NULL, NULL, NULL, '451-2b-roll.svg', '451-2b-roll.svg', '451-2b-roll.svg', '451-2b-roll.svg', 94, 32, 2, '5', '80 m', NULL, NULL, false, '451-2b-roll.svg', '451-2b-roll.svg', '451-2b-roll.svg', '451-2b-roll.svg');

INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.2b-roll-r', true, 'Vorwegweiser ohne Zielangabe (fahrzeugähnliche Geräte) - nach rechts, mit Angabe der Route, mit Distanzangabe', 'Indicateur de direction avancé sans mention de la destination (engins assimilés à des véhicules) - à droite, avec indication de l''itinéraire, avec indication de la distance', 'Segnale di preavviso senza destinazione (mezzi simili a veicoli) - a destra, con l''indicazione del percorso, con l''indicazione della distanza', NULL, NULL, NULL, NULL, NULL, '451-2b-roll-r.svg', '451-2b-roll-r.svg', '451-2b-roll-r.svg', '451-2b-roll-r.svg', 94, 32, 2, '5', '80 m', NULL, NULL, false, '451-2b-roll-r.svg', '451-2b-roll-r.svg', '451-2b-roll-r.svg', '451-2b-roll-r.svg');

INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.2b-roll-l', true, 'Vorwegweiser ohne Zielangabe (fahrzeugähnliche Geräte) - nach links, mit Angabe der Route, mit Distanzangabe', 'Indicateur de direction avancé sans mention de la destination (engins assimilés à des véhicules) - à gauche, avec indication de l''itinéraire, avec indication de la distance', 'Segnale di preavviso senza destinazione (mezzi simili a veicoli) - a sinistra, con l''indicazione del percorso, con l''indicazione della distanza', NULL, NULL, NULL, NULL, NULL, '451-2b-roll-l.svg', '451-2b-roll-l.svg', '451-2b-roll-l.svg', '451-2b-roll-l.svg', 94, 32, 2, '5', '80 m', NULL, NULL, false, '451-2b-roll-l.svg', '451-2b-roll-l.svg', '451-2b-roll-l.svg', '451-2b-roll-l.svg');

-- half right / half left (obliques)
INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.2b-roll-hr', true, 'Vorwegweiser ohne Zielangabe (fahrzeugähnliche Geräte) - nach halb-rechts, mit Angabe der Route, mit Distanzangabe', 'Indicateur de direction avancé sans mention de la destination (engins assimilés à des véhicules) - légèrement à droite, avec indication de l''itinéraire, avec indication de la distance', 'Segnale di preavviso senza destinazione (mezzi simili a veicoli) - mezzo a destra, con l''indicazione del percorso, con l''indicazione della distanza', NULL, NULL, NULL, NULL, NULL, '451-2b-roll-hr.svg', '451-2b-roll-hr.svg', '451-2b-roll-hr.svg', '451-2b-roll-hr.svg', 94, 32, 2, '5', '80 m', NULL, NULL, false, '451-2b-roll-hr.svg', '451-2b-roll-hr.svg', '451-2b-roll-hr.svg', '451-2b-roll-hr.svg');

INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.2b-roll-hl', true, 'Vorwegweiser ohne Zielangabe (fahrzeugähnliche Geräte) - nach halb-links, mit Angabe der Route, mit Distanzangabe', 'Indicateur de direction avancé sans mention de la destination (engins assimilés à des véhicules) - légèrement à gauche, avec indication de l''itinéraire, avec indication de la distance', 'Segnale di preavviso senza destinazione (mezzi simili a veicoli) - mezzo a sinistra, con l''indicazione del percorso, con l''indicazione della distanza', NULL, NULL, NULL, NULL, NULL, '451-2b-roll-hl.svg', '451-2b-roll-hl.svg', '451-2b-roll-hl.svg', '451-2b-roll-hl.svg', 94, 32, 2, '5', '80 m', NULL, NULL, false, '451-2b-roll-hl.svg', '451-2b-roll-hl.svg', '451-2b-roll-hl.svg', '451-2b-roll-hl.svg');

-- 4.51.3
INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.3-roll', true, 'Bestätigungstafel (fahrzeugähnliche Geräte)', 'Plaque de confirmation (engins assimilés à des véhicules)', 'Cartello di conferma (mezzi simili a veicoli)', NULL, NULL, NULL, NULL, NULL, '451-3-roll.svg', '451-3-roll.svg', '451-3-roll.svg', '451-3-roll.svg', 32, 32, 0, NULL, NULL, NULL, NULL, false, '451-3-roll.svg', '451-3-roll.svg', '451-3-roll.svg', '451-3-roll.svg');

INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.3a-roll', true, 'Bestätigungstafel (fahrzeugähnliche Geräte) mit Angabe der Route', 'Plaque de confirmation (engins assimilés à des véhicules) avec indication de l''itinéraire', 'Cartello di conferma (mezzi simili a veicoli) con l''indicazione del percorso', NULL, NULL, NULL, NULL, NULL, '451-3a-roll.svg', '451-3a-roll.svg', '451-3a-roll.svg', '451-3a-roll.svg', 48, 32, 1, '3', NULL, NULL, NULL, false, '451-3a-roll.svg', '451-3a-roll.svg', '451-3a-roll.svg', '451-3a-roll.svg');

INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.3-vel-roll', true, 'Bestätigungstafel (Fahrrad, fahrzeugähnliche Geräte)', 'Plaque de confirmation (vélo, engins assimilés à des véhicules)', 'Cartello di conferma (bicicletta, mezzi simili a veicoli)', NULL, NULL, NULL, NULL, NULL, '451-3-vel-roll.svg', '451-3-vel-roll.svg', '451-3-vel-roll.svg', '451-3-vel-roll.svg', 48, 32, 0, NULL, NULL, NULL, NULL, false, '451-3-vel-roll.svg', '451-3-vel-roll.svg', '451-3-vel-roll.svg', '451-3-vel-roll.svg');

-- other combinations of 4.51.3a are summarized as 4.51.3a-comb 
INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4,directional_sign, img_de_right, img_fr_right, img_it_right, img_ro_right) 
VALUES ('4.51.3a-comb', true, 'Bestätigungstafel (Kombination) mit Angabe der Route', 'Plaque de confirmation (combinaison) avec indication de l''itinéraire', 'Cartello di conferma (combinazione) con l''indicazione del percorso', NULL, NULL, NULL, NULL, NULL, '451-3a-comb.svg', '451-3a-comb.svg', '451-3a-comb.svg', '451-3a-comb.svg', 48, 32, 1, '3', NULL, NULL, NULL, false, '451-3a-comb.svg', '451-3a-comb.svg', '451-3a-comb.svg', '451-3a-comb.svg');
