CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS hstore;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";


CREATE SCHEMA signalo_od;
CREATE SCHEMA signalo_vl;
CREATE SCHEMA signalo_sys;