DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'signalo_viewer') THEN
        EXECUTE 'CREATE ROLE signalo_viewer NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION';
    END IF;

    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'signalo_user') THEN
        EXECUTE 'CREATE ROLE signalo_user NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION';
    END IF;

    EXECUTE 'GRANT signalo_viewer TO signalo_user';
END
$$;
