
-- Vermehrung von Fahrstreifen, Augmentation du nombre de voies de circulation - 4.77 1-3
INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4, directional_sign) VALUES ('4.77/01', true, 'Vermehrung von Fahrstreifen (1)', 'Augmentation du nombre de voies de circulation (1)', 'Aumento del numero di corsie di traffico (1)', NULL, NULL, NULL, NULL, NULL, '477-1.svg', '477-1.svg', '477-1.svg', '477-1.svg', 100, 70, 0, NULL, NULL, NULL, NULL, false);
INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4, directional_sign) VALUES ('4.77/02', true, 'Vermehrung von Fahrstreifen (2)', 'Augmentation du nombre de voies de circulation (2)', 'Aumento del numero di corsie di traffico (2)', NULL, NULL, NULL, NULL, NULL, '477-2.svg', '477-2.svg', '477-2.svg', '477-2.svg', 100, 100, 0, NULL, NULL, NULL, NULL, false);
INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4, directional_sign) VALUES ('4.77/03', true, 'Vermehrung von Fahrstreifen (3)', 'Augmentation du nombre de voies de circulation (3)', 'Aumento del numero di corsie di traffico (3)', NULL, NULL, NULL, NULL, NULL, '477-3.svg', '477-3.svg', '477-3.svg', '477-3.svg', 100, 100, 0, NULL, NULL, NULL, NULL, false);

-- Zusammenführung von Fahrbahnen, Convergence de chaussées - 4.77 4-9
INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4, directional_sign) VALUES ('4.77/04', true, 'Zusammenführung von Fahrbahnen (von rechts)', 'Convergence de chaussées (de droite)', 'Convergenza stradale (destra)', NULL, NULL, NULL, NULL, NULL, '477-4.svg', '477-4.svg', '477-4.svg', '477-4.svg', 100, 70, 0, NULL, NULL, NULL, NULL, false);
INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4, directional_sign) VALUES ('4.77/05', true, 'Zusammenführung von Fahrbahnen (von links)', 'Convergence de chaussées (de gauche)', 'Convergenza stradale (sinistra)', NULL, NULL, NULL, NULL, NULL, '477-5.svg', '477-5.svg', '477-5.svg', '477-5.svg', 100, 70, 0, NULL, NULL, NULL, NULL, false);
INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4, directional_sign) VALUES ('4.77/06', true, 'Zusammenführung von Fahrbahnen (zwei von rechts)', 'Convergence de chaussées (deux de droite)', 'Convergenza stradale (due a destra)', NULL, NULL, NULL, NULL, NULL, '477-6.svg', '477-6.svg', '477-6.svg', '477-6.svg', 100, 100, 0, NULL, NULL, NULL, NULL, false);
INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4, directional_sign) VALUES ('4.77/07', true, 'Zusammenführung von Fahrbahnen (eine von rechts)', 'Convergence de chaussées (une de droite)', 'Convergenza stradale (una a destra)', NULL, NULL, NULL, NULL, NULL, '477-7.svg', '477-7.svg', '477-7.svg', '477-7.svg', 100, 100, 0, NULL, NULL, NULL, NULL, false);
INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4, directional_sign) VALUES ('4.77/08', true, 'Zusammenführung von Fahrbahnen (eine von links)', 'Convergence de chaussées (une de gauche)', 'Convergenza stradale (una a sinistra)', NULL, NULL, NULL, NULL, NULL, '477-8.svg', '477-8.svg', '477-8.svg', '477-8.svg', 100, 100, 0, NULL, NULL, NULL, NULL, false);
INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4, directional_sign) VALUES ('4.77/09', true, 'Zusammenführung von Fahrbahnen (zwei von links)', 'Convergence de chaussées (deux de gauche)', 'Convergenza stradale (due a sinistra)', NULL, NULL, NULL, NULL, NULL, '477-9.svg', '477-9.svg', '477-9.svg', '477-9.svg', 100, 100, 0, NULL, NULL, NULL, NULL, false);

-- Bestätigung der Anzahl Fahrstreifen, Confirmation du nombre de voies de circulation - 4.77 10-15
INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4, directional_sign) VALUES ('4.77/10', true, 'Bestätigung der Anzahl Fahrstreifen (zwei)', 'Confirmation du nombre de voies de circulation (deux)', 'Conferma del numero di corsie di traffico (due)', NULL, NULL, NULL, NULL, NULL, '477-10.svg', '477-10.svg', '477-10.svg', '477-10.svg', 100, 70, 0, NULL, NULL, NULL, NULL, false);
INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4, directional_sign) VALUES ('4.77/11', true, 'Bestätigung der Anzahl Fahrstreifen (drei)', 'Confirmation du nombre de voies de circulation (trois)', 'Conferma del numero di corsie di traffico (tre)', NULL, NULL, NULL, NULL, NULL, '477-11.svg', '477-11.svg', '477-11.svg', '477-11.svg', 100, 100, 0, NULL, NULL, NULL, NULL, false);
INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4, directional_sign) VALUES ('4.77.1/01', true, 'Bestätigung der Anzahl Fahrstreifen (drei, mit Geschwindigkeitsbegrenzung)', 'Confirmation du nombre de voies de circulation (trois, avec réduction de vitesse)', 'Conferma del numero di corsie di traffico (tre, con riduzione della velocità)', NULL, NULL, NULL, NULL, NULL, '477_1-01.svg', '477_1-01.svg', '477_1-01.svg', '477_1-01.svg', 100, 100, 1, '80', NULL, NULL, NULL, false);
INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4, directional_sign) VALUES ('4.77/12', true, 'Bestätigung der Anzahl Fahrstreifen (zwei, Gegenverkehr)', 'Confirmation du nombre de voies de circulation (deux, circulation à contresens)', 'Conferma del numero di corsie di traffico (due, traffico bidirezionale)', NULL, NULL, NULL, NULL, NULL, '477-12.svg', '477-12.svg', '477-12.svg', '477-12.svg', 100, 70, 0, NULL, NULL, NULL, NULL, false);
INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4, directional_sign) VALUES ('4.77/13', true, 'Bestätigung der Anzahl Fahrstreifen (drei, Gegenverkehr einspurig)', 'Confirmation du nombre de voies de circulation (trois, circulation à contresens une voie)', 'Conferma del numero di corsie di traffico (tre, traffico in controcorrente in una corsia)', NULL, NULL, NULL, NULL, NULL, '477-13.svg', '477-13.svg', '477-13.svg', '477-13.svg', 100, 100, 0, NULL, NULL, NULL, NULL, false);
INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4, directional_sign) VALUES ('4.77/14', true, 'Bestätigung der Anzahl Fahrstreifen (drei, Gegenverkehr zweispurig)', 'Confirmation du nombre de voies de circulation (trois, circulation à contresens deux voies)', 'Conferma del numero di corsie di traffico (tre, traffico in controcorrente in due corsie)', NULL, NULL, NULL, NULL, NULL, '477-14.svg', '477-14.svg', '477-14.svg', '477-14.svg', 100, 100, 0, NULL, NULL, NULL, NULL, false);
INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4, directional_sign) VALUES ('4.77/15', true, 'Bestätigung der Anzahl Fahrstreifen (vier, doppelspurig)', 'Confirmation du nombre de voies de circulation (quatre, double voies)', 'Conferma del numero di corsie di traffico (quattro, doppio binario)', NULL, NULL, NULL, NULL, NULL, '477-15.svg', '477-15.svg', '477-15.svg', '477-15.svg', 100, 125, 0, NULL, NULL, NULL, NULL, false);

-- Verminderung von Fahrstreifen, Diminution du nombre de voies de circulation - 4.77 16-19
INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4, directional_sign) VALUES ('4.77/16', true, 'Verminderung von Fahrstreifen (einer, rechts)', 'Diminution du nombre de voies de circulation (une, droite)', 'Riduzione del numero di corsie di traffico (una, a destra)', NULL, NULL, NULL, NULL, NULL, '477-16.svg', '477-16.svg', '477-16.svg', '477-16.svg', 100, 70, 0, NULL, NULL, NULL, NULL, false);
INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4, directional_sign) VALUES ('4.77/17', true, 'Verminderung von Fahrstreifen (einer, links)', 'Diminution du nombre de voies de circulation (une, gauche)', 'Riduzione del numero di corsie di traffico (una, a sinistra)', NULL, NULL, NULL, NULL, NULL, '477-17.svg', '477-17.svg', '477-17.svg', '477-17.svg', 100, 70, 0, NULL, NULL, NULL, NULL, false);
INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4, directional_sign) VALUES ('4.77/18', true, 'Verminderung von Fahrstreifen (zwei, links)', 'Diminution du nombre de voies de circulation (deux, gauche)', 'Riduzione del numero di corsie di traffico (due, a sinistra)', NULL, NULL, NULL, NULL, NULL, '477-18.svg', '477-18.svg', '477-18.svg', '477-18.svg', 100, 100, 0, NULL, NULL, NULL, NULL, false);
INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4, directional_sign) VALUES ('4.77/19', true, 'Verminderung von Fahrstreifen (einer, links, mit Gegenverkehr)', 'Diminution du nombre de voies de circulation (une, gauche, avec circulation à contresens)', 'Riduzione del numero di corsie di traffico (una, a sinistra, con traffico in controcorrente)', NULL, NULL, NULL, NULL, NULL, '477-19.svg', '477-19.svg', '477-19.svg', '477-19.svg', 100, 100, 0, NULL, NULL, NULL, NULL, false);

-- Anzeige des Fahrstreifenverlaufs, Indication du tracé des voies de circulation - 4.77 20-29
INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4, directional_sign) VALUES ('4.77/20', true, 'Anzeige des Fahrstreifenverlaufs (nach links)', 'Indication du tracé des voies de circulation (à gauche)', 'Segnaletica di corsia (sinistra)', NULL, NULL, NULL, NULL, NULL, '477-20.svg', '477-20.svg', '477-20.svg', '477-20.svg', 100, 80, 0, NULL, NULL, NULL, NULL, false);
INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4, directional_sign) VALUES ('4.77/21', true, 'Anzeige des Fahrstreifenverlaufs (nach rechts)', 'Indication du tracé des voies de circulation (à droite)', 'Segnaletica di corsia (destra)', NULL, NULL, NULL, NULL, NULL, '477-21.svg', '477-21.svg', '477-21.svg', '477-21.svg', 100, 80, 0, NULL, NULL, NULL, NULL, false);
INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4, directional_sign) VALUES ('4.77/22', true, 'Anzeige des Fahrstreifenverlaufs (ausweichen nach links)', 'Indication du tracé des voies de circulation (évitement à gauche)', 'Segnaletica di corsia (sterzare a sinistra)', NULL, NULL, NULL, NULL, NULL, '477-22.svg', '477-22.svg', '477-22.svg', '477-22.svg', 100, 80, 0, NULL, NULL, NULL, NULL, false);
INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4, directional_sign) VALUES ('4.77/23', true, 'Anzeige des Fahrstreifenverlaufs (ausweichen nach rechts)', 'Indication du tracé des voies de circulation (évitement à droite)', 'Segnaletica di corsia (sterzare a destra)', NULL, NULL, NULL, NULL, NULL, '477-23.svg', '477-23.svg', '477-23.svg', '477-23.svg', 100, 80, 0, NULL, NULL, NULL, NULL, false);

INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4, directional_sign) VALUES ('4.77/24', true, 'Verschwenkung von Fahrstreifen (Hindernis links)', 'Déplacement latéral des voies de circulation (obstacle à gauche)', 'Spostamento laterale delle corsie di traffico (ostacolo a sinistra)', NULL, NULL, NULL, NULL, NULL, '477-24.svg', '477-24.svg', '477-24.svg', '477-24.svg', 100, 80, 0, NULL, NULL, NULL, NULL, false);
INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4, directional_sign) VALUES ('4.77/25', true, 'Verschwenkung von Fahrstreifen (Hindernis mittig)', 'Déplacement latéral des voies de circulation (obstacle au milieu)', 'Spostamento laterale delle corsie di traffico (nel mezzo)', NULL, NULL, NULL, NULL, NULL, '477-25.svg', '477-25.svg', '477-25.svg', '477-25.svg', 100, 100, 0, NULL, NULL, NULL, NULL, false);

INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4, directional_sign) VALUES ('4.77/26', true, 'Überleitung und Rückführung von Fahrstreifen (einspurig)', 'Dégagement et retour des voies de circulation (à une voie)', 'Sgombero e ripristino delle corsie di traffico (a una corsia)', NULL, NULL, NULL, NULL, NULL, '477-26.svg', '477-26.svg', '477-26.svg', '477-26.svg', 100, 72, 0, NULL, NULL, NULL, NULL, false);
INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4, directional_sign) VALUES ('4.77/27', true, 'Überleitung und Rückführung von Fahrstreifen (doppelspurig nach links)', 'Dégagement et retour des voies de circulation (à deux voies à gauche)', 'Sgombero e ripristino delle corsie di traffico (a due corsie a sinistra)', NULL, NULL, NULL, NULL, NULL, '477-27.svg', '477-27.svg', '477-27.svg', '477-27.svg', 100, 85, 0, NULL, NULL, NULL, NULL, false);
INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4, directional_sign) VALUES ('4.77/28-1', true, 'Überleitung und Rückführung von Fahrstreifen (eine Spur)', 'Dégagement et retour des voies de circulation (une voie)', 'Sgombero e ripristino delle corsie di traffico (due corsie)', NULL, NULL, NULL, NULL, NULL, '477-28-1.svg', '477-28-1.svg', '477-28-1.svg', '477-28-1.svg', 100, 100, 0, NULL, NULL, NULL, NULL, false);
INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4, directional_sign) VALUES ('4.77/28-2', true, 'Überleitung und Rückführung von Fahrstreifen (Spurverengung)', 'Dégagement et retour des voies de circulation (rétrécissement de la voie)', 'Sgombero e ripristino delle corsie di traffico (restringimento della corsia)', NULL, NULL, NULL, NULL, NULL, '477-28-2.svg', '477-28-2.svg', '477-28-2.svg', '477-28-2.svg', 100, 100, 1, '2 m', NULL, NULL, NULL, false);
INSERT INTO signalo_db.vl_official_sign (id, active, value_de, value_fr, value_it, value_ro, description_de, description_fr, description_it, description_ro, img_de, img_fr, img_it, img_ro, img_height, img_width, no_dynamic_inscription, default_inscription1, default_inscription2, default_inscription3, default_inscription4, directional_sign) VALUES ('4.77/29', true, 'Überleitung und Rückführung von Fahrstreifen (doppelspurig nach rechts)', 'Dégagement et retour des voies de circulation (à deux voies à droite)', 'Sgombero e ripristino delle corsie di traffico (a due corsie a destra)', NULL, NULL, NULL, NULL, NULL, '477-29.svg', '477-29.svg', '477-29.svg', '477-29.svg', 100, 85, 0, NULL, NULL, NULL, NULL, false);

-- Set 4.77 exemple to inactive
UPDATE signalo_db.vl_official_sign 
SET active = false where id = '4.77'