-- create vl_tube_type

DROP TABLE IF EXISTS  signalo_db.vl_support_tube_type;
CREATE TABLE IF NOT EXISTS signalo_db.vl_support_tube_type (
    id integer NOT NULL,
    active boolean DEFAULT true,
    value_fr text,
    value_de text
);

ALTER TABLE signalo_db.vl_support_tube_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME signalo_db.vl_support_tube_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

SELECT pg_catalog.setval('signalo_db.vl_support_tube_type_id_seq', 1, false);

ALTER TABLE ONLY signalo_db.vl_support_tube_type
    ADD CONSTRAINT support_tube_type_pkey PRIMARY KEY (id);

INSERT INTO signalo_db.vl_support_tube_type (id, active, value_fr, value_de) VALUES (1, true, 'inconnu', 'unbekannt');
INSERT INTO signalo_db.vl_support_tube_type (id, active, value_fr, value_de) VALUES (2, true, 'autre', 'andere');
INSERT INTO signalo_db.vl_support_tube_type (id, active, value_fr, value_de) VALUES (3, true, 'à déterminer', 'zu bestimmen');
INSERT INTO signalo_db.vl_support_tube_type (id, active, value_fr, value_de) VALUES (4, true, 'Ø 2', 'Ø 2');
INSERT INTO signalo_db.vl_support_tube_type (id, active, value_fr, value_de) VALUES (5, true, 'Ø 2.5', 'Ø 2.5');
INSERT INTO signalo_db.vl_support_tube_type (id, active, value_fr, value_de) VALUES (6, true, 'Ø 3', 'Ø 3');

